import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { CSSTransition } from "react-transition-group";

import styles from "styles/Home.module.scss";

import { Banner } from "components";

let arr = new Array(4).fill().map((_, i) => i + 1);

export default function Home() {
  const [heroData, setHeroData] = useState(1);

  useEffect(() => {
    let interval;
    interval = setInterval(() => {
      setHeroData((prev) => (prev === 4 ? 1 : prev + 1));
    }, 5000);
    return () => {
      if (interval) clearInterval(interval);
    };
  }, []);

  const handleBtnBannerClick = () => {};

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffeefy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonLabel={"View stores nearby"}
          handleBtnBannerClick={handleBtnBannerClick}
        />
        {arr.map((i) => (
          <CSSTransition
            key={i}
            in={i === heroData}
            timeout={500}
            classNames={{
              enterActive: styles.heroImageEnterActive,
              enterDone: styles.heroImageEnterDone,
              exitActive: styles.heroImageExitActive,
              exitDone: styles.heroImageExitDone,
            }}
            unmountOnExit
          >
            <div className={styles.heroImage}>
              <Image
                src={`/static/Hero${i}.png`}
                alt="Hero image"
                width={500}
                height={500}
              />
            </div>
          </CSSTransition>
        ))}
      </main>
    </div>
  );
}
